* My Emacs Config
Welcome to my emacs setup! Sorry it's not literate, and always in a mess, but hopefully it helps!

This config was sorted in least to most likely to break... as I test stuff with my init.el and restart often.
I use hs-minor-mode(code-folding) and parentheses and outli-mode to sort and view this config, so if you don't use them, good luck!
I use emacs-mac, so there's mac-win.el being run before startup to help me with configuration too!
Xah-fly-keys sets some modes as well, so I didn't set them.

** Main Features
package manager:
- straight
configuration macros:
- leaf (trying to transition to this, mostly done.)
- once
- use-package (ugh can't get rid of custom-face forms)

** What each file is for
- early-init.el is for optimisations like disabling loading with package.el so that the init loads faster 
- init.el is the 1 massive config file. download it and use emacs to browse it!
- templates is for tempel.el, have a look at the cryptic snippet templates written in lisp data!
- straight folder contains my lockfiles, I've never used them and I regret it.
*** I use no-littering
a package that sets most packages' data directories to /var and config ones to /etc
  - etc/eshell/alias holds eshell aliases

